dedupePeerDependents: true
packages:
  - apps/*
  - packages/*
  - docs
  - "!docs/templates/*"
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@openapitools/openapi-generator-cli"
  - "@scarf/scarf"
  - "@sentry-internal/node-cpu-profiler"
  - "@sentry/cli"
  - "@tree-sitter-grammars/tree-sitter-yaml"
  - bigint-buffer
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - sharp
  - tree-sitter
  - tree-sitter-json
  - utf-8-validate