packages:
  - apps/*
  # had to exclude expo rn from monorepo becasue it can only works with react 19.0.0
  # having 2 versions of react will cause duplication of wagmi and cause react context referencing error.
  - "!apps/demo-rn-expo"
  - packages/*
  - examples/*
  - docs
  - "!docs/templates/*"
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@openapitools/openapi-generator-cli"
  - "@scarf/scarf"
  - "@sentry-internal/node-cpu-profiler"
  - "@sentry/cli"
  - "@tree-sitter-grammars/tree-sitter-yaml"
  - bigint-buffer
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - sharp
  - tree-sitter
  - tree-sitter-json
  - utf-8-validate
