import { setupGetChannel } from "./channels/[id]/get";
import { setupGetChannels } from "./channels/get";
import { setupGetComment } from "./comments/[commentId]/get";
import setupGetComments from "./comments/get";
import setupGetCommentReplies from "./comments/replies/get";
import setupGetApprovals from "./approvals/get";
import { type OpenAPIHono } from "@hono/zod-openapi";
import { setupGetAuthor } from "./authors/get";
import { setupMarkAuthorAsMuted } from "./muted-accounts/post";
import { setupUnmuteAccount } from "./muted-accounts/delete";
import { setupGetMutedAccount } from "./muted-accounts/get";
import { setupGetPendingModerationComments } from "./moderate-comments/get";
import { setupChangeCommentModerationStatus } from "./moderate-comments/[commentId]/patch";
import { setupGetModerateComment } from "./moderate-comments/[commentId]/get";
import { setupWebhook } from "./webhook/post";
import { setupGetAutocomplete } from "./autocomplete/get";
import { setupReportComment } from "./comments/[commentId]/reports/post";
import { setupGetReports } from "./reports/get";
import { setupGetReport } from "./reports/[reportId]/get";
import { setupPatchReport } from "./reports/[reportId]/patch";
import { setupAdminBotWebhook } from "./webhook/bot/post";
import { setupAuthSiweNonce } from "./auth/siwe/nonce/get";
import { setupAuthSiweVerify } from "./auth/siwe/verify/post";
import { setupAuthSiweRefresh } from "./auth/siwe/refresh/post";
import { setupUsersMe } from "./users/me/get";
import { setupUsersMeDelete } from "./users/me/delete";
import { setupAppCreate } from "./apps/post";
import { setupAppDelete } from "./apps/[id]/delete";
import { setupAppSecretRefresh } from "./apps/[id]/secret/refresh/post";
import { setupAppSecretReveal } from "./apps/[id]/secret/reveal/post";
import { setupAppsGet } from "./apps/get";
import { setupAppGet } from "./apps/[id]/get";
import { setupAppWebhookCreate } from "./apps/[id]/webhooks/create";
import { setupAppWebhooksGet } from "./apps/[id]/webhooks/get";
import { setupAppWebhookDelete } from "./apps/[id]/webhooks/[id]/delete";
import { setupAppWebhookGet } from "./apps/[id]/webhooks/[id]/get";
import { setupAppWebhookPatch } from "./apps/[id]/webhooks/[id]/patch";
import { setupAppWebhookTest } from "./apps/[id]/webhooks/[id]/test/post";
import { setupAppUpdate } from "./apps/[id]/patch";
import { setupAppWebhookDeliveryAttemptsGet } from "./apps/[id]/webhooks/[id]/deliveries/attempts/get";
import { setupAppWebhookDeliveryRetry } from "./apps/[id]/webhooks/[id]/deliveries/[id]/retry/post";
import { setupAppWebhookDeliveryGet } from "./apps/[id]/webhooks/[id]/deliveries/[id]/get";
import { setupAppWebhookDeliveriesGet } from "./apps/[id]/webhooks/[id]/deliveries/get";
import { setupNotificationsSeenPost } from "./notifications/seen/post";
import { setupNotificationsGet } from "./notifications/get";
import { setupAppNotificationsGroupedGet } from "./notifications/grouped/get";
import { setupAnalyticsKpiDeliveriesGet } from "./analytics/kpi/deliveries/get";
import { setupAnalyticsKpiEventualSuccessGet } from "./analytics/kpi/eventual-success/get";
import { setupAnalyticsKpiFirstAttemptSuccessGet } from "./analytics/kpi/first-attempt-success/get";
import { setupAnalyticsKpiE2ELatencyGet } from "./analytics/kpi/e2e-latency/get";
import { setupAnalyticsKpiBacklogGet } from "./analytics/kpi/backlog/get";
import { setupAnalyticsKpiDeliveredUnderMinuteGet } from "./analytics/kpi/delivered-under-minute/get";
import { setupAnalyticsVolumeGet } from "./analytics/volume/get";
import { setupAnalyticsTerminalGet } from "./analytics/terminal/get";
import { setupAnalyticsSuccessRatesGet } from "./analytics/success-rates/get";
import { setupAnalyticsE2ELatencyGet } from "./analytics/e2e-latency/get";
import { setupAnalyticsSlaBandsGet } from "./analytics/sla-bands/get";
import { setupAnalyticsErrorsGet } from "./analytics/errors/get";

export default function setupRestAPI(app: OpenAPIHono) {
  setupGetChannel(app);
  setupGetChannels(app);
  setupGetComment(app);
  setupGetComments(app);
  setupGetCommentReplies(app);
  setupGetApprovals(app);
  setupGetAuthor(app);
  setupGetMutedAccount(app);
  setupUnmuteAccount(app);
  setupMarkAuthorAsMuted(app);
  setupGetPendingModerationComments(app);
  setupChangeCommentModerationStatus(app);
  setupGetModerateComment(app);
  setupWebhook(app);
  setupGetAutocomplete(app);
  setupReportComment(app);
  setupGetReports(app);
  setupGetReport(app);
  setupPatchReport(app);
  setupAdminBotWebhook(app);
  setupAuthSiweNonce(app);
  setupAuthSiweVerify(app);
  setupAuthSiweRefresh(app);
  setupUsersMe(app);
  setupUsersMeDelete(app);
  setupAppCreate(app);
  setupAppDelete(app);
  setupAppSecretRefresh(app);
  setupAppSecretReveal(app);
  setupAppUpdate(app);
  setupAppsGet(app);
  setupAppGet(app);
  setupAppWebhookCreate(app);
  setupAppWebhooksGet(app);
  setupAppWebhookDelete(app);
  setupAppWebhookGet(app);
  setupAppWebhookPatch(app);
  setupAppWebhookTest(app);
  setupAppWebhookDeliveryGet(app);
  setupAppWebhookDeliveryAttemptsGet(app);
  setupAppWebhookDeliveryRetry(app);
  setupAppWebhookDeliveriesGet(app);
  setupAnalyticsKpiDeliveriesGet(app);
  setupAnalyticsKpiEventualSuccessGet(app);
  setupAnalyticsKpiFirstAttemptSuccessGet(app);
  setupAnalyticsKpiE2ELatencyGet(app);
  setupAnalyticsKpiBacklogGet(app);
  setupAnalyticsKpiDeliveredUnderMinuteGet(app);
  setupAnalyticsVolumeGet(app);
  setupAnalyticsTerminalGet(app);
  setupAnalyticsSuccessRatesGet(app);
  setupAnalyticsE2ELatencyGet(app);
  setupAnalyticsSlaBandsGet(app);
  setupAnalyticsErrorsGet(app);
  setupNotificationsSeenPost(app);
  setupNotificationsGet(app);
  setupAppNotificationsGroupedGet(app);

  return app;
}
