import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ethereum Comments Protocol",
  description: "ECP demo generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <main className="flex-1">
            <Providers>{children}</Providers>
          </main>
          <footer className="py-4 text-center text-xs text-gray-500 border-t border-gray-200">
            <a href="/terms" className="hover:text-gray-700 transition-colors">
              Demo App Terms & Conditions
            </a>
          </footer>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
