import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ethereum Comments Protocol",
  description: "ECP demo generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
      >
        <div className="min-h-screen flex flex-col">
          <div className="flex flex-col flex-1 my-8 gap-6">
            <Providers>{children}</Providers>
            <footer className="text-center text-xs text-gray-500">
              <a
                href="/terms"
                className="text-gray-400 hover:text-gray-700 transition-colors"
              >
                Demo App Terms & Conditions
              </a>
            </footer>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
