export const MAX_COMMENT_LENGTH = 1000;
export const TRUNCATE_COMMENT_LENGTH = 200;
export const TRUNCATE_COMMENT_LINES = 5;
export const COMMENTS_PER_PAGE = 10;
export const MAX_INITIAL_REPLIES_ON_PARENT_COMMENT = 3;
export const NEW_COMMENTS_BY_AUTHOR_CHECK_INTERVAL = 60000; // 1 minute
export const NEW_COMMENTS_CHECK_INTERVAL = 30000; // 30 seconds
